name: Create daily files
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/58 */23 * * *'

jobs:
  create_daily_files:
    name: Create daily files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run
        run: python create-daily-files.py

      - name: Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git config pull.rebase false
          git status
          git pull origin $GITHUB_REF
          git add ./
          git commit -m "add daily scraper files" && git push || true
        shell: bash
